name: Main Deploy Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  update_docker_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: byvoxel/php_test:latest

  deploy:
    name: Deploy Docker Container to EC2
    runs-on: ubuntu-latest
    needs: update_docker_image

    steps:
      - name: Parse EC2 Instances
        id: parse_ec2
        run: |
          echo "instances='${{ secrets.EC2_INSTANCES }}'" >> $GITHUB_ENV

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ matrix.instance }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker stop php_test || true
            sudo docker rm php_test || true
            sudo docker pull byvoxel/php_test:latest
            sudo docker run -d --name php_test -p 80:80 byvoxel/php_test:latest

    strategy:
      matrix:
        instance: ${{ fromJson(secrets.EC2_INSTANCES) }}   # Corrige esta línea
